//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM_WMS_SRG_ProductDispatchGP
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private IM_WMS_SRG_ProductDispatchGP.FaultMessageList[] FaultMessageListArrayField;
        
        private IM_WMS_SRG_ProductDispatchGP.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IM_WMS_SRG_ProductDispatchGP.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IM_WMS_SRG_ProductDispatchGP.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private IM_WMS_SRG_ProductDispatchGP.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IM_WMS_SRG_ProductDispatchGP.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private IM_WMS_SRG_ProductDispatchGP.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IM_WMS_SRG_ProductDispatchGP.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatch")]
    public interface IM_WMS_SRG_ProductDispatch
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM_WMS_SRG_ProductDispatch/initDiarios", ReplyAction="http://tempuri.org/IM_WMS_SRG_ProductDispatch/initDiariosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IM_WMS_SRG_ProductDispatchGP.AifFault), Action="http://tempuri.org/IM_WMS_SRG_ProductDispatch/initDiariosAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchInitDiariosResponse> initDiariosAsync(IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchInitDiariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM_WMS_SRG_ProductDispatch/createTransfer", ReplyAction="http://tempuri.org/IM_WMS_SRG_ProductDispatch/createTransferResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IM_WMS_SRG_ProductDispatchGP.AifFault), Action="http://tempuri.org/IM_WMS_SRG_ProductDispatch/createTransferAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchCreateTransferResponse> createTransferAsync(IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchCreateTransferRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IM_WMS_SRG_ProductDispatchInitDiariosRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IM_WMS_SRG_ProductDispatchInitDiariosRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IM_WMS_SRG_ProductDispatchGP.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _accion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _dataValidationXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _xml;
        
        public IM_WMS_SRG_ProductDispatchInitDiariosRequest()
        {
        }
        
        public IM_WMS_SRG_ProductDispatchInitDiariosRequest(IM_WMS_SRG_ProductDispatchGP.CallContext CallContext, string _accion, string _dataValidationXML, string _xml)
        {
            this.CallContext = CallContext;
            this._accion = _accion;
            this._dataValidationXML = _dataValidationXML;
            this._xml = _xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IM_WMS_SRG_ProductDispatchInitDiariosResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IM_WMS_SRG_ProductDispatchInitDiariosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IM_WMS_SRG_ProductDispatchInitDiariosResponse()
        {
        }
        
        public IM_WMS_SRG_ProductDispatchInitDiariosResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IM_WMS_SRG_ProductDispatchCreateTransferRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IM_WMS_SRG_ProductDispatchCreateTransferRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IM_WMS_SRG_ProductDispatchGP.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IM_WMS_SRG_ProductDispatchCreateTransferRequest()
        {
        }
        
        public IM_WMS_SRG_ProductDispatchCreateTransferRequest(IM_WMS_SRG_ProductDispatchGP.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IM_WMS_SRG_ProductDispatchCreateTransferResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IM_WMS_SRG_ProductDispatchCreateTransferResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IM_WMS_SRG_ProductDispatchCreateTransferResponse()
        {
        }
        
        public IM_WMS_SRG_ProductDispatchCreateTransferResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IM_WMS_SRG_ProductDispatchChannel : IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatch, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class M_WMS_SRG_ProductDispatchClient : System.ServiceModel.ClientBase<IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatch>, IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatch
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public M_WMS_SRG_ProductDispatchClient() : 
                base(M_WMS_SRG_ProductDispatchClient.GetDefaultBinding(), M_WMS_SRG_ProductDispatchClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IM_WMS_SRG_ProductDispatch.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public M_WMS_SRG_ProductDispatchClient(EndpointConfiguration endpointConfiguration) : 
                base(M_WMS_SRG_ProductDispatchClient.GetBindingForEndpoint(endpointConfiguration), M_WMS_SRG_ProductDispatchClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public M_WMS_SRG_ProductDispatchClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(M_WMS_SRG_ProductDispatchClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public M_WMS_SRG_ProductDispatchClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(M_WMS_SRG_ProductDispatchClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public M_WMS_SRG_ProductDispatchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchInitDiariosResponse> IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatch.initDiariosAsync(IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchInitDiariosRequest request)
        {
            return base.Channel.initDiariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchInitDiariosResponse> initDiariosAsync(IM_WMS_SRG_ProductDispatchGP.CallContext CallContext, string _accion, string _dataValidationXML, string _xml)
        {
            IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchInitDiariosRequest inValue = new IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchInitDiariosRequest();
            inValue.CallContext = CallContext;
            inValue._accion = _accion;
            inValue._dataValidationXML = _dataValidationXML;
            inValue._xml = _xml;
            return ((IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatch)(this)).initDiariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchCreateTransferResponse> IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatch.createTransferAsync(IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchCreateTransferRequest request)
        {
            return base.Channel.createTransferAsync(request);
        }
        
        public System.Threading.Tasks.Task<IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchCreateTransferResponse> createTransferAsync(IM_WMS_SRG_ProductDispatchGP.CallContext CallContext, string _receiveXML)
        {
            IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchCreateTransferRequest inValue = new IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatchCreateTransferRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IM_WMS_SRG_ProductDispatchGP.IM_WMS_SRG_ProductDispatch)(this)).createTransferAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IM_WMS_SRG_ProductDispatch))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IM_WMS_SRG_ProductDispatch))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://gim-dev-aos:8201/DynamicsAx/Services/IM_WMS_SRG_ProductDispatchGP");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return M_WMS_SRG_ProductDispatchClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IM_WMS_SRG_ProductDispatch);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return M_WMS_SRG_ProductDispatchClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IM_WMS_SRG_ProductDispatch);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IM_WMS_SRG_ProductDispatch,
        }
    }
}
