//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMGetTransferJournalAsgGPService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private IMGetTransferJournalAsgGPService.FaultMessageList[] FaultMessageListArrayField;
        
        private IMGetTransferJournalAsgGPService.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IMGetTransferJournalAsgGPService.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IMGetTransferJournalAsgGPService.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private IMGetTransferJournalAsgGPService.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IMGetTransferJournalAsgGPService.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private IMGetTransferJournalAsgGPService.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IMGetTransferJournalAsgGPService.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg")]
    public interface IMGetTransferJournalAsg
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMGetTransferJournalAsg/getAllSites", ReplyAction="http://tempuri.org/IMGetTransferJournalAsg/getAllSitesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMGetTransferJournalAsgGPService.AifFault), Action="http://tempuri.org/IMGetTransferJournalAsg/getAllSitesAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllSitesResponse> getAllSitesAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllSitesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMGetTransferJournalAsg/getClosedTransferJournalByWorkerId", ReplyAction="http://tempuri.org/IMGetTransferJournalAsg/getClosedTransferJournalByWorkerIdResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMGetTransferJournalAsgGPService.AifFault), Action="http://tempuri.org/IMGetTransferJournalAsg/getClosedTransferJournalByWorkerIdAifF" +
            "aultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdResponse> getClosedTransferJournalByWorkerIdAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMGetTransferJournalAsg/getTransferJournalHeader", ReplyAction="http://tempuri.org/IMGetTransferJournalAsg/getTransferJournalHeaderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMGetTransferJournalAsgGPService.AifFault), Action="http://tempuri.org/IMGetTransferJournalAsg/getTransferJournalHeaderAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalHeaderResponse> getTransferJournalHeaderAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalHeaderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMGetTransferJournalAsg/getAllLocations", ReplyAction="http://tempuri.org/IMGetTransferJournalAsg/getAllLocationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMGetTransferJournalAsgGPService.AifFault), Action="http://tempuri.org/IMGetTransferJournalAsg/getAllLocationsAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllLocationsResponse> getAllLocationsAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllLocationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMGetTransferJournalAsg/getTransferJournalLines", ReplyAction="http://tempuri.org/IMGetTransferJournalAsg/getTransferJournalLinesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMGetTransferJournalAsgGPService.AifFault), Action="http://tempuri.org/IMGetTransferJournalAsg/getTransferJournalLinesAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLinesResponse> getTransferJournalLinesAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMGetTransferJournalAsg/getUpdateWMSLocationId", ReplyAction="http://tempuri.org/IMGetTransferJournalAsg/getUpdateWMSLocationIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMGetTransferJournalAsgGPService.AifFault), Action="http://tempuri.org/IMGetTransferJournalAsg/getUpdateWMSLocationIdAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetUpdateWMSLocationIdResponse> getUpdateWMSLocationIdAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetUpdateWMSLocationIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMGetTransferJournalAsg/getDeleteLine", ReplyAction="http://tempuri.org/IMGetTransferJournalAsg/getDeleteLineResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMGetTransferJournalAsgGPService.AifFault), Action="http://tempuri.org/IMGetTransferJournalAsg/getDeleteLineAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetDeleteLineResponse> getDeleteLineAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetDeleteLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMGetTransferJournalAsg/getTransferJournalLine2", ReplyAction="http://tempuri.org/IMGetTransferJournalAsg/getTransferJournalLine2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMGetTransferJournalAsgGPService.AifFault), Action="http://tempuri.org/IMGetTransferJournalAsg/getTransferJournalLine2AifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLine2Response> getTransferJournalLine2Async(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLine2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMGetTransferJournalAsg/getAllWMSLocation", ReplyAction="http://tempuri.org/IMGetTransferJournalAsg/getAllWMSLocationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMGetTransferJournalAsgGPService.AifFault), Action="http://tempuri.org/IMGetTransferJournalAsg/getAllWMSLocationAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllWMSLocationResponse> getAllWMSLocationAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllWMSLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMGetTransferJournalAsg/getPostTransferJournal", ReplyAction="http://tempuri.org/IMGetTransferJournalAsg/getPostTransferJournalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMGetTransferJournalAsgGPService.AifFault), Action="http://tempuri.org/IMGetTransferJournalAsg/getPostTransferJournalAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetPostTransferJournalResponse> getPostTransferJournalAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetPostTransferJournalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMGetTransferJournalAsg/getOpenTransferJournalByWorkerId", ReplyAction="http://tempuri.org/IMGetTransferJournalAsg/getOpenTransferJournalByWorkerIdRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(IMGetTransferJournalAsgGPService.AifFault), Action="http://tempuri.org/IMGetTransferJournalAsg/getOpenTransferJournalByWorkerIdAifFau" +
            "ltFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdResponse> getOpenTransferJournalByWorkerIdAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetAllSitesRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetAllSitesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IMGetTransferJournalAsgGPService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IMGetTransferJournalAsgGetAllSitesRequest()
        {
        }
        
        public IMGetTransferJournalAsgGetAllSitesRequest(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetAllSitesResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetAllSitesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IMGetTransferJournalAsgGetAllSitesResponse()
        {
        }
        
        public IMGetTransferJournalAsgGetAllSitesResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IMGetTransferJournalAsgGPService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdRequest()
        {
        }
        
        public IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdRequest(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdResponse()
        {
        }
        
        public IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetTransferJournalHeaderRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetTransferJournalHeaderRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IMGetTransferJournalAsgGPService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IMGetTransferJournalAsgGetTransferJournalHeaderRequest()
        {
        }
        
        public IMGetTransferJournalAsgGetTransferJournalHeaderRequest(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetTransferJournalHeaderResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetTransferJournalHeaderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IMGetTransferJournalAsgGetTransferJournalHeaderResponse()
        {
        }
        
        public IMGetTransferJournalAsgGetTransferJournalHeaderResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetAllLocationsRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetAllLocationsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IMGetTransferJournalAsgGPService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IMGetTransferJournalAsgGetAllLocationsRequest()
        {
        }
        
        public IMGetTransferJournalAsgGetAllLocationsRequest(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetAllLocationsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetAllLocationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IMGetTransferJournalAsgGetAllLocationsResponse()
        {
        }
        
        public IMGetTransferJournalAsgGetAllLocationsResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetTransferJournalLinesRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetTransferJournalLinesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IMGetTransferJournalAsgGPService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IMGetTransferJournalAsgGetTransferJournalLinesRequest()
        {
        }
        
        public IMGetTransferJournalAsgGetTransferJournalLinesRequest(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetTransferJournalLinesResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetTransferJournalLinesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IMGetTransferJournalAsgGetTransferJournalLinesResponse()
        {
        }
        
        public IMGetTransferJournalAsgGetTransferJournalLinesResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetUpdateWMSLocationIdRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetUpdateWMSLocationIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IMGetTransferJournalAsgGPService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IMGetTransferJournalAsgGetUpdateWMSLocationIdRequest()
        {
        }
        
        public IMGetTransferJournalAsgGetUpdateWMSLocationIdRequest(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetUpdateWMSLocationIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetUpdateWMSLocationIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IMGetTransferJournalAsgGetUpdateWMSLocationIdResponse()
        {
        }
        
        public IMGetTransferJournalAsgGetUpdateWMSLocationIdResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetDeleteLineRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetDeleteLineRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IMGetTransferJournalAsgGPService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IMGetTransferJournalAsgGetDeleteLineRequest()
        {
        }
        
        public IMGetTransferJournalAsgGetDeleteLineRequest(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetDeleteLineResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetDeleteLineResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IMGetTransferJournalAsgGetDeleteLineResponse()
        {
        }
        
        public IMGetTransferJournalAsgGetDeleteLineResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetTransferJournalLine2Request", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetTransferJournalLine2Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IMGetTransferJournalAsgGPService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IMGetTransferJournalAsgGetTransferJournalLine2Request()
        {
        }
        
        public IMGetTransferJournalAsgGetTransferJournalLine2Request(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetTransferJournalLine2Response", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetTransferJournalLine2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IMGetTransferJournalAsgGetTransferJournalLine2Response()
        {
        }
        
        public IMGetTransferJournalAsgGetTransferJournalLine2Response(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetAllWMSLocationRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetAllWMSLocationRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IMGetTransferJournalAsgGPService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IMGetTransferJournalAsgGetAllWMSLocationRequest()
        {
        }
        
        public IMGetTransferJournalAsgGetAllWMSLocationRequest(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetAllWMSLocationResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetAllWMSLocationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IMGetTransferJournalAsgGetAllWMSLocationResponse()
        {
        }
        
        public IMGetTransferJournalAsgGetAllWMSLocationResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetPostTransferJournalRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetPostTransferJournalRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IMGetTransferJournalAsgGPService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IMGetTransferJournalAsgGetPostTransferJournalRequest()
        {
        }
        
        public IMGetTransferJournalAsgGetPostTransferJournalRequest(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetPostTransferJournalResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetPostTransferJournalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IMGetTransferJournalAsgGetPostTransferJournalResponse()
        {
        }
        
        public IMGetTransferJournalAsgGetPostTransferJournalResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IMGetTransferJournalAsgGPService.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdRequest()
        {
        }
        
        public IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdRequest(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdResponse()
        {
        }
        
        public IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IMGetTransferJournalAsgChannel : IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MGetTransferJournalAsgClient : System.ServiceModel.ClientBase<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg>, IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MGetTransferJournalAsgClient() : 
                base(MGetTransferJournalAsgClient.GetDefaultBinding(), MGetTransferJournalAsgClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IMGetTransferJournalAsg.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MGetTransferJournalAsgClient(EndpointConfiguration endpointConfiguration) : 
                base(MGetTransferJournalAsgClient.GetBindingForEndpoint(endpointConfiguration), MGetTransferJournalAsgClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MGetTransferJournalAsgClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MGetTransferJournalAsgClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MGetTransferJournalAsgClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MGetTransferJournalAsgClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MGetTransferJournalAsgClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllSitesResponse> IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg.getAllSitesAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllSitesRequest request)
        {
            return base.Channel.getAllSitesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllSitesResponse> getAllSitesAsync(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllSitesRequest inValue = new IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllSitesRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg)(this)).getAllSitesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdResponse> IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg.getClosedTransferJournalByWorkerIdAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdRequest request)
        {
            return base.Channel.getClosedTransferJournalByWorkerIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdResponse> getClosedTransferJournalByWorkerIdAsync(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdRequest inValue = new IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetClosedTransferJournalByWorkerIdRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg)(this)).getClosedTransferJournalByWorkerIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalHeaderResponse> IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg.getTransferJournalHeaderAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalHeaderRequest request)
        {
            return base.Channel.getTransferJournalHeaderAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalHeaderResponse> getTransferJournalHeaderAsync(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalHeaderRequest inValue = new IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalHeaderRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg)(this)).getTransferJournalHeaderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllLocationsResponse> IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg.getAllLocationsAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllLocationsRequest request)
        {
            return base.Channel.getAllLocationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllLocationsResponse> getAllLocationsAsync(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllLocationsRequest inValue = new IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllLocationsRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg)(this)).getAllLocationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLinesResponse> IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg.getTransferJournalLinesAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLinesRequest request)
        {
            return base.Channel.getTransferJournalLinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLinesResponse> getTransferJournalLinesAsync(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLinesRequest inValue = new IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLinesRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg)(this)).getTransferJournalLinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetUpdateWMSLocationIdResponse> IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg.getUpdateWMSLocationIdAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetUpdateWMSLocationIdRequest request)
        {
            return base.Channel.getUpdateWMSLocationIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetUpdateWMSLocationIdResponse> getUpdateWMSLocationIdAsync(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetUpdateWMSLocationIdRequest inValue = new IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetUpdateWMSLocationIdRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg)(this)).getUpdateWMSLocationIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetDeleteLineResponse> IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg.getDeleteLineAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetDeleteLineRequest request)
        {
            return base.Channel.getDeleteLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetDeleteLineResponse> getDeleteLineAsync(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetDeleteLineRequest inValue = new IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetDeleteLineRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg)(this)).getDeleteLineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLine2Response> IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg.getTransferJournalLine2Async(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLine2Request request)
        {
            return base.Channel.getTransferJournalLine2Async(request);
        }
        
        public System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLine2Response> getTransferJournalLine2Async(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLine2Request inValue = new IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetTransferJournalLine2Request();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg)(this)).getTransferJournalLine2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllWMSLocationResponse> IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg.getAllWMSLocationAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllWMSLocationRequest request)
        {
            return base.Channel.getAllWMSLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllWMSLocationResponse> getAllWMSLocationAsync(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllWMSLocationRequest inValue = new IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetAllWMSLocationRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg)(this)).getAllWMSLocationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetPostTransferJournalResponse> IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg.getPostTransferJournalAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetPostTransferJournalRequest request)
        {
            return base.Channel.getPostTransferJournalAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetPostTransferJournalResponse> getPostTransferJournalAsync(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetPostTransferJournalRequest inValue = new IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetPostTransferJournalRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg)(this)).getPostTransferJournalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdResponse> IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg.getOpenTransferJournalByWorkerIdAsync(IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdRequest request)
        {
            return base.Channel.getOpenTransferJournalByWorkerIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdResponse> getOpenTransferJournalByWorkerIdAsync(IMGetTransferJournalAsgGPService.CallContext CallContext, string _receiveXML)
        {
            IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdRequest inValue = new IMGetTransferJournalAsgGPService.IMGetTransferJournalAsgGetOpenTransferJournalByWorkerIdRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IMGetTransferJournalAsgGPService.IMGetTransferJournalAsg)(this)).getOpenTransferJournalByWorkerIdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IMGetTransferJournalAsg))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IMGetTransferJournalAsg))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://gim-dev-aos:8201/DynamicsAx/Services/IMGetTransferJournalAsgGP");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MGetTransferJournalAsgClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IMGetTransferJournalAsg);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MGetTransferJournalAsgClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IMGetTransferJournalAsg);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IMGetTransferJournalAsg,
        }
    }
}
