//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM_WMS_SRG_ChangeOpEST
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private IM_WMS_SRG_ChangeOpEST.FaultMessageList[] FaultMessageListArrayField;
        
        private IM_WMS_SRG_ChangeOpEST.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IM_WMS_SRG_ChangeOpEST.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IM_WMS_SRG_ChangeOpEST.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private IM_WMS_SRG_ChangeOpEST.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IM_WMS_SRG_ChangeOpEST.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private IM_WMS_SRG_ChangeOpEST.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IM_WMS_SRG_ChangeOpEST.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOp")]
    public interface IM_WMS_SRG_ChangeEstOp
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM_WMS_SRG_ChangeEstOp/changeOpStateToNotifyAsFinished", ReplyAction="http://tempuri.org/IM_WMS_SRG_ChangeEstOp/changeOpStateToNotifyAsFinishedResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(IM_WMS_SRG_ChangeOpEST.AifFault), Action="http://tempuri.org/IM_WMS_SRG_ChangeEstOp/changeOpStateToNotifyAsFinishedAifFault" +
            "Fault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedResponse> changeOpStateToNotifyAsFinishedAsync(IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM_WMS_SRG_ChangeEstOp/changeOpStateToStartedUp", ReplyAction="http://tempuri.org/IM_WMS_SRG_ChangeEstOp/changeOpStateToStartedUpResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IM_WMS_SRG_ChangeOpEST.AifFault), Action="http://tempuri.org/IM_WMS_SRG_ChangeEstOp/changeOpStateToStartedUpAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpResponse> changeOpStateToStartedUpAsync(IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IM_WMS_SRG_ChangeEstOp/quantityAdjustmenByOrder", ReplyAction="http://tempuri.org/IM_WMS_SRG_ChangeEstOp/quantityAdjustmenByOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IM_WMS_SRG_ChangeOpEST.AifFault), Action="http://tempuri.org/IM_WMS_SRG_ChangeEstOp/quantityAdjustmenByOrderAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderResponse> quantityAdjustmenByOrderAsync(IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IM_WMS_SRG_ChangeOpEST.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveXML;
        
        public IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedRequest()
        {
        }
        
        public IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedRequest(IM_WMS_SRG_ChangeOpEST.CallContext CallContext, string _receiveXML)
        {
            this.CallContext = CallContext;
            this._receiveXML = _receiveXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedResponse()
        {
        }
        
        public IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IM_WMS_SRG_ChangeOpEST.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveToReverseXML;
        
        public IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpRequest()
        {
        }
        
        public IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpRequest(IM_WMS_SRG_ChangeOpEST.CallContext CallContext, string _receiveToReverseXML)
        {
            this.CallContext = CallContext;
            this._receiveToReverseXML = _receiveToReverseXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpResponse()
        {
        }
        
        public IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public IM_WMS_SRG_ChangeOpEST.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _receiveToReverseXML;
        
        public IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderRequest()
        {
        }
        
        public IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderRequest(IM_WMS_SRG_ChangeOpEST.CallContext CallContext, string _receiveToReverseXML)
        {
            this.CallContext = CallContext;
            this._receiveToReverseXML = _receiveToReverseXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderResponse()
        {
        }
        
        public IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IM_WMS_SRG_ChangeEstOpChannel : IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOp, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class M_WMS_SRG_ChangeEstOpClient : System.ServiceModel.ClientBase<IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOp>, IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOp
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public M_WMS_SRG_ChangeEstOpClient() : 
                base(M_WMS_SRG_ChangeEstOpClient.GetDefaultBinding(), M_WMS_SRG_ChangeEstOpClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IM_WMS_SRG_ChangeEstOp.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public M_WMS_SRG_ChangeEstOpClient(EndpointConfiguration endpointConfiguration) : 
                base(M_WMS_SRG_ChangeEstOpClient.GetBindingForEndpoint(endpointConfiguration), M_WMS_SRG_ChangeEstOpClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public M_WMS_SRG_ChangeEstOpClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(M_WMS_SRG_ChangeEstOpClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public M_WMS_SRG_ChangeEstOpClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(M_WMS_SRG_ChangeEstOpClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public M_WMS_SRG_ChangeEstOpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedResponse> IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOp.changeOpStateToNotifyAsFinishedAsync(IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedRequest request)
        {
            return base.Channel.changeOpStateToNotifyAsFinishedAsync(request);
        }
        
        public System.Threading.Tasks.Task<IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedResponse> changeOpStateToNotifyAsFinishedAsync(IM_WMS_SRG_ChangeOpEST.CallContext CallContext, string _receiveXML)
        {
            IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedRequest inValue = new IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToNotifyAsFinishedRequest();
            inValue.CallContext = CallContext;
            inValue._receiveXML = _receiveXML;
            return ((IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOp)(this)).changeOpStateToNotifyAsFinishedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpResponse> IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOp.changeOpStateToStartedUpAsync(IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpRequest request)
        {
            return base.Channel.changeOpStateToStartedUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpResponse> changeOpStateToStartedUpAsync(IM_WMS_SRG_ChangeOpEST.CallContext CallContext, string _receiveToReverseXML)
        {
            IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpRequest inValue = new IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpChangeOpStateToStartedUpRequest();
            inValue.CallContext = CallContext;
            inValue._receiveToReverseXML = _receiveToReverseXML;
            return ((IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOp)(this)).changeOpStateToStartedUpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderResponse> IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOp.quantityAdjustmenByOrderAsync(IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderRequest request)
        {
            return base.Channel.quantityAdjustmenByOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderResponse> quantityAdjustmenByOrderAsync(IM_WMS_SRG_ChangeOpEST.CallContext CallContext, string _receiveToReverseXML)
        {
            IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderRequest inValue = new IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOpQuantityAdjustmenByOrderRequest();
            inValue.CallContext = CallContext;
            inValue._receiveToReverseXML = _receiveToReverseXML;
            return ((IM_WMS_SRG_ChangeOpEST.IM_WMS_SRG_ChangeEstOp)(this)).quantityAdjustmenByOrderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IM_WMS_SRG_ChangeEstOp))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IM_WMS_SRG_ChangeEstOp))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://gim-dev-aos:8201/DynamicsAx/Services/IM_WMS_SRG_ChangEstOP");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return M_WMS_SRG_ChangeEstOpClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IM_WMS_SRG_ChangeEstOp);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return M_WMS_SRG_ChangeEstOpClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IM_WMS_SRG_ChangeEstOp);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IM_WMS_SRG_ChangeEstOp,
        }
    }
}
